version: '2.1'

services:
  # Based on https://realpython.com/blog/python/django-development-with-docker-compose-and-machine/
  {{ project_name }}_postgis:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - {{ project_name }}_data:/var/lib/postgresql/data
      - ./logs/postgresql:/var/log/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"

  {{ project_name }}_redis:
    image: redis:3.2.11-alpine
    volumes:
      - ./logs/redis:/var/log/redis

  {{ project_name }}_web:
    build:
      context: .
      dockerfile: ./compose/django/dev/Dockerfile
  #  command: gunicorn {{ project_name }}.wsgi:application -w 4 -t 120 -e DJANGO_SETTINGS_MODULE={{ project_name }}.settings.production -b :8000
    command: python3 manage.py runserver 0.0.0.0:8000 --settings={{ project_name }}.settings.local
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    depends_on:
      - {{ project_name }}_postgis
      - {{ project_name }}_redis


volumes:
  {{ project_name }}_data: